title: Wina Aaron # your name (or website title) here
 # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Undergraduate student at The University of Chicago pursuing a Bachelor's degree in Data Science with a minor in Statistics. I have a strong foundation in data analysis, machine learning, and statistical modeling. 
  <br>
  I have gained hands-on experience with a variety of programming languages and tools such as Python, R, SQL, and GeoDa, allowing me to handle everything from data wrangling to data engineering. 
  <br>
  <a href="https://www.linkedin.com/in/wina-aaron-918b5127a">View My LinkedIn Profile</a> 
logo: "https://github.com/Wina-Aaron/Wina-Aaron.github.io/raw/main/IMG_3162.png"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
